apiVersion: v2
name: ssh-workspace
description: SSH accessible workspace environment
type: application
version: 0.6.0
appVersion: "0.6.0"
icon: https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/gnometerminal.svg

keywords:
  - ssh
  - workspace
  - development
  - terminal

maintainers:
  - name: Nakamura Kazutaka
    email: kaznak.at.work@ipebble.org

sources:
  - https://github.com/kaznak/helm-ssh-workspace

annotations:
  category: Development
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Configurable SSH StrictModes setting for ReadWriteMany volume compatibility
  artifacthub.io/images: |
    - name: ssh-workspace
      image: ghcr.io/kaznak/ssh-workspace:0.6.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/kaznak/helm-ssh-workspace/tree/main/helm/ssh-workspace
    - name: Docker Image
      url: https://github.com/kaznak/helm-ssh-workspace/pkgs/container/ssh-workspace
