# Default values for ssh-workspace

image:
  repository: ghcr.io/kaznak/helm-ssh-workspace/ssh-workspace
  tag: ""  # When empty, defaults to Chart.appVersion
  pullPolicy: IfNotPresent
  pullSecrets: []

# User configuration (required)
user:
  name: ""  # Required: Username for SSH access (e.g., "myuser")
  uid: null  # Optional: User ID (auto-assigned if not specified)
  gid: null  # Optional: Group ID (auto-assigned if not specified)
  shell: /bin/bash  # Default login shell
  additionalGroups: []  # Additional groups for the user
  sudo: false  # Enable sudo privileges

# SSH configuration (required)
ssh:
  publicKeys: []  # Required: SSH public keys (array)
  # Example:
  # - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHs5e0OWn1ybIZdO1l1S0Z1w4h4h4h4h4h4h4h4h4h4h user@example.com"
  port: 2222  # SSH port
  strictModes: true  # SSH StrictModes setting (true for strict permission checks, false for relaxed)
  config: {}  # Additional SSH configuration

# Persistence configuration
persistence:
  enabled: false  # Enable persistent home directory
  existingClaim: ""  # Use existing PVC instead of creating new one (optional)
  subPath: ""  # Mount subdirectory from PVC (optional)
  size: 10Gi  # Storage size for new PVC (ignored if existingClaim is set)
  storageClass: ""  # Storage class for new PVC (use default if empty)
  accessModes:
    - ReadWriteOnce


# Security configuration
security:
  level: standard  # Security level: basic, standard, high
  securityContext: {}  # Additional Container Security Context (overrides defaults)
  podSecurityContext: {}  # Additional Pod Security Context (added to defaults)

# Audit configuration
audit:
  enabled: false  # Enable Linux audit logging for SSH sessions (may cause issues in Kubernetes)

# Service configuration
service:
  type: ClusterIP  # Service type: ClusterIP, NodePort, LoadBalancer
  port: 2222  # Service port

# Resource limits and requests
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Timezone configuration
timezone: UTC

# Monitoring configuration
monitoring:
  enabled: false  # Enable ssh_exporter sidecar
  port: 9312  # Metrics port
  serviceMonitor:
    enabled: false  # Create ServiceMonitor for Prometheus
    interval: 30s

# Ingress configuration
ingress:
  enabled: false  # Enable Ingress
  className: ""  # Ingress class name
  annotations: {}
  hosts: []
  tls: []

# Additional labels and annotations
labels: {}
annotations: {}

# Additional environment variables
extraEnvVars: []
# Example:
# extraEnvVars:
#   - name: SSH_WORKSPACE_DEBUG_CHMOD_FAILURES
#     value: "true"

# Cluster configuration
cluster:
  domain: cluster.local  # Kubernetes cluster domain suffix

# Test configuration
tests:
  rbac:
    create: true  # Create ServiceAccount and RBAC for tests
  
  # Resource validation test configuration
  resourceValidation:
    enabled: true  # Enable resource validation tests (basic infrastructure checks)
  
  # SSH internal validation test configuration  
  sshValidation:
    enabled: true  # Enable SSH internal validation tests (SSH server configuration and permissions)
  
  # Test SSH keys for automated testing (optional)
  # These keys are added in addition to the main publicKeys for testing purposes
  testKeys:
    enabled: false
    # Method 1: Direct key pairs - both public and private keys needed for testing
    keyPairs: []
    # Example:
    # keyPairs:
    #   - publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGrShAQgt+9ZuPDQ1L2KrSwKxL8BEcqhytt7X3ZLZxai test-key@helm-test"
    #     privateKey: |
    #       -----BEGIN OPENSSH PRIVATE KEY-----
    #       b3BlbnNzaC1QlkeXktZZlnBUKmhp4AAAAC1lZQI5NTE5AAAAIGrShAQgt+9ZuPDQ1L2K
    #       rSwKxL8BEcqhytt7X3ZLZxaiAAAAFHRlc3Qta2V5QGhlbG0tdGVzdA==
    #       -----END OPENSSH PRIVATE KEY-----
    # Method 2: Existing Secret reference (recommended for production)
    existingSecret: ""  # Name of existing Secret containing test SSH keys
    # When existingSecret is specified, keyPairs is ignored
    # Expected Secret format:
    # data:
    #   public-key-0: <base64-encoded-public-key>
    #   private-key-0: <base64-encoded-private-key>
    #   public-key-1: <base64-encoded-public-key>  # Additional key pairs
    #   private-key-1: <base64-encoded-private-key>
  
  # SSH connectivity test configuration
  sshConnectivity:
    enabled: false  # Enable SSH connectivity tests (requires tests.testKeys.enabled: true)
  
  # User workspace functionality test configuration
  workspaceFunctionality:
    enabled: false  # Enable workspace functionality tests (requires tests.testKeys.enabled: true)
    networkTest:
      enabled: false  # Enable external network connectivity tests