{{- if .Values.ssh.publicKeys.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.publicKeys.secretName | default (printf "%s-ssh-pubkeys" (include "ssh-workspace.fullname" .)) }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
type: Opaque
data:
  authorized_keys: {{ .Values.ssh.publicKeys.authorizedKeys | b64enc }}
{{- end }}