{{/*
SSH Private Keys Secret Template
SSH private key Secret storage [[see:R2L7-PRIVKEY]](../docs/design.md#R2L7-PRIVKEY)
values.yaml private key configuration [[see:W7N2-PRIVKEY]](../README.ja.md#W7N2-PRIVKEY)
Multiple private key support [[see:Q9M4-MULTIPRIVKEY]](../README.ja.md#Q9M4-MULTIPRIVKEY)
Private key mounting strategy [[see:B8W3-PRIVMOUNT]](../docs/design.md#B8W3-PRIVMOUNT)
*/}}
{{- if .Values.ssh.privateKeys.keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.privateKeys.secretName | default (printf "%s-ssh-privkeys" (include "ssh-workspace.fullname" .)) }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $filename, $content := .Values.ssh.privateKeys.keys }}
  {{ $filename }}: {{ $content | b64enc }}
  {{- end }}
{{- end }}