{{- if .Values.ssh.privateKeys.keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.privateKeys.secretName | default (printf "%s-ssh-privkeys" (include "ssh-workspace.fullname" .)) }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $filename, $content := .Values.ssh.privateKeys.keys }}
  {{ $filename }}: {{ $content | b64enc }}
  {{- end }}
{{- end }}