{{/*
SSH Public Keys Secret Template
SSH public key Secret storage [[see:P5Q8-PUBKEY]](../docs/design.md#P5Q8-PUBKEY)
values.yaml public key configuration [[see:K9T4-PUBKEY]](../README.ja.md#K9T4-PUBKEY)
Multiple public key support [[see:M6L5-MULTIKEY]](../README.ja.md#M6L5-MULTIKEY)
Public key mounting strategy [[see:D4K3-KEYMOUNT]](../docs/design.md#D4K3-KEYMOUNT)
*/}}
{{- if .Values.ssh.publicKeys.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh.publicKeys.secretName | default (printf "%s-ssh-pubkeys" (include "ssh-workspace.fullname" .)) }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
type: Opaque
data:
  authorized_keys: {{ .Values.ssh.publicKeys.authorizedKeys | b64enc }}
{{- end }}