{{/*
SSH Workspace ServiceAccount Template
Minimal security permissions [see:J5N4-HOSTPERM]
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssh-workspace.serviceAccountName" . }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}