apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-workspace.fullname" . }}-host-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data: {}