{{- include "ssh-workspace.validateValues" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssh-workspace.fullname" . }}-ssh-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  authorized_keys: |
{{- range .Values.ssh.publicKeys }}
    {{ . }}
{{- end }}
{{- if .Values.tests.testKeys.enabled }}
{{- range .Values.tests.testKeys.keyPairs }}
    {{ .publicKey }}
{{- end }}
{{- end }}
---
{{- if or .Values.ssh.config (not (eq .Values.ssh.strictModes nil)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssh-workspace.fullname" . }}-ssh-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssh-workspace.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  custom_config: |
{{- if not (eq .Values.ssh.strictModes nil) }}
    StrictModes {{ if .Values.ssh.strictModes }}yes{{ else }}no{{ end }}
{{- end }}
{{- range $key, $value := .Values.ssh.config }}
    {{ $key }} {{ $value }}
{{- end }}
{{- end }}