---
# Default values for ssh-workspace
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Image configuration
image:
  repository: ghcr.io/kaznak/ssh-workspace
  pullPolicy: Always  # Default for production, overridden locally
  tag: "v0.7.5"

# Image pull secrets
imagePullSecrets: []

# Override the chart name
nameOverride: ""
fullnameOverride: ""

# SSH configuration
ssh:
  # SSH server port [see:B3Q8-PORT]
  port: 2222

  # SSH host keys configuration [see:V4J1-HOSTKEY]
  hostKeys:
    # Secret name for SSH host keys [see:W5X2-SECRET]
    # If not specified, defaults to "{{ .Release.Name }}-ssh-hostkeys"
    secretName: ""
    # Auto-generate host keys if secret doesn't exist [see:T8Q4-AUTOGEN]
    autoGenerate: true

  # SSH user public keys configuration [see:K9T4-PUBKEY]
  publicKeys:
    # Secret name for SSH public keys [see:P5Q8-PUBKEY]
    # If not specified, defaults to "{{ .Release.Name }}-ssh-pubkeys"
    secretName: ""
    # Direct specification of authorized_keys content [see:M6L5-MULTIKEY]
    authorizedKeys: ""

  # SSH user private keys configuration [see:W7N2-PRIVKEY]
  privateKeys:
    # Secret name for SSH private keys [see:R2L7-PRIVKEY]
    # If not specified, defaults to "{{ .Release.Name }}-ssh-privkeys"
    secretName: ""
    # Direct specification of private keys [see:Q9M4-MULTIPRIVKEY]
    keys: {}
    # Example:
    # keys:
    #   id_rsa: |
    #     -----BEGIN OPENSSH PRIVATE KEY-----
    #     ...
    #     -----END OPENSSH PRIVATE KEY-----
    #   id_ed25519: |
    #     -----BEGIN OPENSSH PRIVATE KEY-----
    #     ...
    #     -----END OPENSSH PRIVATE KEY-----

# User configuration [see:Y4F1-USER]
user:
  # Username [see:G8W5-USERNAME]
  name: developer
  # User ID [see:Z2S7-UID]
  uid: 1000
  # Group ID [see:A9T3-GID]
  gid: 1000

# Service configuration
service:
  # Service type [see:E4L7-CLUSTER]
  type: ClusterIP
  # Service port
  port: 22
  # Target port (container port)
  targetPort: 2222

# Home directory configuration [see:V5Q3-HOME]
homeDirectory:
  # Storage type: "emptyDir" or "persistentVolume" [see:T1H8-EMPTY]
  type: emptyDir

  # EmptyDir configuration
  emptyDir:
    sizeLimit: 1Gi

  # PersistentVolume configuration [see:R7P4-STORAGE]
  persistentVolume:
    # Use existing PVC instead of creating new one
    # If specified, the PVC template will not be created
    existingClaim: ""
    # Storage class [see:R7P4-STORAGE]
    storageClass: ""
    # Storage size
    size: 5Gi
    # Access modes
    accessModes:
      - ReadWriteOnce
    # Subdirectory mount [see:C6B2-SUBDIR]
    subPath: ""

# Resource limits and requests [see:J1X6-LIMIT]
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi

# Job resources
jobResources:
  # Host key generation job
  hostKeyGeneration:
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 50Mi

  # Key validation job
  keyValidation:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 500Mi
    requests:
      cpu: 25m
      memory: 32Mi
      ephemeral-storage: 50Mi

# Security context for main SSH workspace container (requires root for user management)
mainSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  capabilities:
    add: ["CHOWN", "DAC_OVERRIDE"]

# Security context for job containers (temporarily using root for Dropbear key operations)
jobSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  capabilities:
    add: ["CHOWN", "DAC_OVERRIDE"]

# Pod security context for main deployment (requires root)
mainPodSecurityContext:
  runAsNonRoot: false
  supplementalGroups: []

# Pod security context for jobs (temporarily using root for Dropbear key operations)
jobPodSecurityContext:
  runAsNonRoot: false
  supplementalGroups: []

# Health check configuration [see:Q1P4-HEALTH]
healthCheck:
  # Liveness probe [see:L3F8-LIVENESS]
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  # Readiness probe [see:R6Q9-READINESS]
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

# Service account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Replicas (fixed to 1) [see:J8R2-DEPLOY]
replicaCount: 1

# Update strategy [see:Y3S2-DOWN]
updateStrategy:
  type: Recreate
