name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/ssh-workspace/**'
      - '.github/workflows/helm-release.yml'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.1'

      - name: Lint Helm Chart
        run: |
          helm lint helm/ssh-workspace

      - name: Package Helm Chart
        run: |
          helm package helm/ssh-workspace --destination .helm-packages

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm Chart to GHCR
        run: |
          for pkg in .helm-packages/*.tgz; do
            if [ -f "$pkg" ]; then
              helm push "$pkg" oci://ghcr.io/${{ github.repository_owner }}/charts
            fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .helm-packages/*.tgz
          generate_release_notes: true