name: GitHub Pages Helm Repository

on:
  push:
    branches:
      - main
    paths:
      - 'helm/ssh-workspace/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.1'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create Helm repository
        run: |
          mkdir -p helm-repo
          helm package helm/ssh-workspace --destination helm-repo/
          helm repo index helm-repo/ --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: helm-repo/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4